/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapa_ps1;

import javax.swing.JOptionPane;

/**
 *
 * @author eliel
 */
public class Mapa1 extends javax.swing.JFrame {
    int pontasA=0,pontasB=0, placarA=0,placarB=0;
    /**
     * Creates new form Mapa
     */
    public Mapa1() {
        initComponents();
 
    }

    
    public void pontosA(int valor){
        pontasA = Integer.parseInt(txtpontosA.getText())+valor;
        txtpontosA.setText(String.valueOf(pontasA));
        placarA(pontasA);
    }
    public void pontosB(int valor){
         pontasB = Integer.parseInt(txtpontosB.getText())+valor;
        txtpontosB.setText(String.valueOf(pontasB));
        placarB(pontasB);
    }
    void placarA(int valor){
       if(valor>=12){
           placarA=Integer.parseInt(txtplacarA.getText())+1;
           txtplacarA.setText(String.valueOf(placarA));
           JOptionPane.showMessageDialog(this, "Equipe A venceu a Rodada");
            zerarpontos();
           
           if(placarA==2){
                JOptionPane.showMessageDialog(this, "Equipe A venceu o Jogo\n PARABENS!");
                txtplacarA.setText("0");
                txtplacarB.setText("0");
       }
       }
    }
    void placarB(int valor){
       if(valor>=12){
           placarB=Integer.parseInt(txtplacarB.getText())+1;
           txtplacarB.setText(String.valueOf(placarB));
           JOptionPane.showMessageDialog(rootPane, "Equipe B venceu a Rodada");
            zerarpontos();
                      
           if(placarB==2){
                JOptionPane.showMessageDialog(this, "Equipe B venceu o Jogo\n PARABENS!");
                txtplacarB.setText("0");
                txtplacarA.setText("0");
           }
           
       }
    }
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EQUIPEA = new javax.swing.JPanel();
        btn_menos1A = new javax.swing.JButton();
        btn_mais1A = new javax.swing.JButton();
        btn_mais3A = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtpontosA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EQUIPEB = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtpontosB = new javax.swing.JTextField();
        btn_mais3B = new javax.swing.JButton();
        btn_mais1B = new javax.swing.JButton();
        btn_menos1B = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        PLACAR = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtplacarB = new javax.swing.JTextField();
        txtplacarA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_limparB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EQUIPEA.setBackground(new java.awt.Color(255, 0, 51));
        EQUIPEA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_menos1A.setText("-1");
        btn_menos1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menos1AActionPerformed(evt);
            }
        });
        EQUIPEA.add(btn_menos1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        btn_mais1A.setText("+1");
        btn_mais1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mais1AActionPerformed(evt);
            }
        });
        EQUIPEA.add(btn_mais1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        btn_mais3A.setText("+3");
        btn_mais3A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mais3AActionPerformed(evt);
            }
        });
        EQUIPEA.add(btn_mais3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOME DA EQUIPE A");
        EQUIPEA.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 234, -1));

        txtpontosA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpontosA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpontosA.setText("0");
        txtpontosA.setEnabled(false);
        EQUIPEA.add(txtpontosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 84, 166, 34));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PONTOS");
        EQUIPEA.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 20));

        getContentPane().add(EQUIPEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, 170));

        EQUIPEB.setBackground(new java.awt.Color(0, 51, 204));
        EQUIPEB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NOME DA EQUIPE B");
        EQUIPEB.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 234, -1));

        txtpontosB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpontosB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpontosB.setText("0");
        txtpontosB.setEnabled(false);
        EQUIPEB.add(txtpontosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 84, 166, 34));

        btn_mais3B.setText("+3");
        btn_mais3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mais3BActionPerformed(evt);
            }
        });
        EQUIPEB.add(btn_mais3B, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        btn_mais1B.setText("+1");
        btn_mais1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mais1BActionPerformed(evt);
            }
        });
        EQUIPEB.add(btn_mais1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        btn_menos1B.setText("-1");
        btn_menos1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menos1BActionPerformed(evt);
            }
        });
        EQUIPEB.add(btn_menos1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PONTOS");
        EQUIPEB.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 20));

        getContentPane().add(EQUIPEB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 125, -1, 170));

        PLACAR.setBackground(new java.awt.Color(204, 204, 255));
        PLACAR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PLACAR");
        PLACAR.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 490, -1));

        txtplacarB.setEditable(false);
        txtplacarB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtplacarB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtplacarB.setText("0");
        txtplacarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplacarBActionPerformed(evt);
            }
        });
        PLACAR.add(txtplacarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 70, 57));

        txtplacarA.setEditable(false);
        txtplacarA.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtplacarA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtplacarA.setText("0");
        txtplacarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplacarAActionPerformed(evt);
            }
        });
        PLACAR.add(txtplacarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 70, 57));

        jLabel3.setText("VS");
        PLACAR.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        getContentPane().add(PLACAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 494, 119));

        btn_limparB.setBackground(new java.awt.Color(0, 0, 0));
        btn_limparB.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparB.setText("LIMPAR PONTOS");
        btn_limparB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparBActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limparB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 475, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtplacarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplacarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplacarBActionPerformed

    private void txtplacarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplacarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplacarAActionPerformed

    private void btn_menos1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menos1BActionPerformed
        pontosB(-1);
    }//GEN-LAST:event_btn_menos1BActionPerformed

    private void btn_menos1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menos1AActionPerformed
        pontosA(-1);
    }//GEN-LAST:event_btn_menos1AActionPerformed

    private void btn_mais3AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mais3AActionPerformed
       pontosA(3);
    }//GEN-LAST:event_btn_mais3AActionPerformed

    private void btn_mais1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mais1AActionPerformed
       pontosA(1);
    }//GEN-LAST:event_btn_mais1AActionPerformed

    private void btn_mais3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mais3BActionPerformed
         pontosB(3);
    }//GEN-LAST:event_btn_mais3BActionPerformed

    private void btn_mais1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mais1BActionPerformed
         pontosB(1);
    }//GEN-LAST:event_btn_mais1BActionPerformed

    private void btn_limparBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparBActionPerformed
          zerarpontos();
    }//GEN-LAST:event_btn_limparBActionPerformed
    public void zerarpontos(){
                 txtpontosA.setText("0");
           txtpontosB.setText("0");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mapa1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EQUIPEA;
    private javax.swing.JPanel EQUIPEB;
    private javax.swing.JPanel PLACAR;
    private javax.swing.JButton btn_limparB;
    private javax.swing.JButton btn_mais1A;
    private javax.swing.JButton btn_mais1B;
    private javax.swing.JButton btn_mais3A;
    private javax.swing.JButton btn_mais3B;
    private javax.swing.JButton btn_menos1A;
    private javax.swing.JButton btn_menos1B;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtplacarA;
    private javax.swing.JTextField txtplacarB;
    private javax.swing.JTextField txtpontosA;
    private javax.swing.JTextField txtpontosB;
    // End of variables declaration//GEN-END:variables
}
